### ISSUE TITLE
There is no ProtExcluder.pl

### ISSUE THREAD

**Issue by Ozzborne** [KrabbenhoftLab/genome_annotation_pipeline#1]
**Hi Dan, 
I keep getting the following error when running step 2 of the pipeline:** 

-----------------------------------------------------
Input is being processed as unpaired
Time:                           2.619 seconds.
Reads Processed:        570k    217.70k reads/sec
Bases Processed:        206m    78.72m bases/sec
Reads Out:          569888
Bases Out:          206062128
/home/krablab/Documents/CO_data/LT_repeats/Ref_genome//scripts/run_repeatMasker.sh: line 36: /home/krablab/Documents/apps/ProtExcluder1.2/ProtExcluder.pl: No such file or directory
RepeatMasker::setspecies: Could not find user specified library ../Lake_trout_RepeatModeler/Lake_trout_REPEAT_LIBRARY-families.fanoProtFinal, or the file is empty.
gzip: ./RMask_denovoPrediction_protFiltered/*.cat.gz: No such file or directory
gzip: ./RMask_denovoPlusDfam/*.cat.gz: No such file or directory
cat: './RMask_denovoPrediction_protFiltered/*.cat': No such file or directory
cat: './RMask_denovoPlusDfam/*.cat': No such file or directory
gzip: ./RMask_denovoPrediction_protFiltered/*.cat: No such file or directory
gzip: ./RMask_denovoPlusDfam/*.cat: No such file or directory
-----------------------------------------------------

**This issue is arising because there is no scripts/run_repeatMasker.sh file in the  the following directory :/home/krablab/Documents/apps/ProtExcluder/**

**Below is the command (Line 36 of the run_repeatMasker.sh**
-------------------------------------------------------
# note that ProtExcluder requires "esl-sfetch" from the Easel library
# on Bottlerocket, located at "/home/krablab/miniconda2/envs/hmmer/bin/esl-sfetch"
/home/krablab/Documents/apps/ProtExcluder/ProtExcluder.pl ${SPECIES}_blastx_uniprot_TEfiltered_e10.out ../${SPECIES}_RepeatModeler/${REPEAT_LIBRARY_NAME}-families.fa_

**I tried downloading the ProtExcluder.pl script from this link https://github.com/NBISweden/ProtExcluder/blob/master/ProtExcluder.pl but even after adding that to the aforementioned directory and changing the file permissions, it still didn't work.**
-----------------------------------------------------
Executing driver.FilterReadsByName [in=uniprot_sprot.fasta, out=uniprot_sprot.TEfiltered.fasta, names=transposable,transposase, substring=name, ignorejunk]

Exception in thread "main" java.lang.AssertionError: File uniprot_sprot.TEfiltered.fasta exists and overwrite=false
        at shared.Tools.testOutputFiles(Tools.java:127)
        at driver.FilterReadsByName.<init>(FilterReadsByName.java:225)
        at driver.FilterReadsByName.main(FilterReadsByName.java:40)
sh: 1: matchtract.pl: not found
sh: 1: countaanu.pl: not found
sh: 1: rmlowcomplexitymathc.pl: not found
sh: 1: blastformatProt.pl: not found
sh: 1: rmlowcomfromBF.pl: not found
sh: 1: mergequeryBF.pl: not found
sh: 1: unmatchedregionBF.pl: not found
Can't exec "mspesl-sfetch.pl": No such file or directory at /home/krablab/Documents/apps/ProtExcluder1.2/ProtExcluder.pl line 33.
sh: 1: mergeunmatchedregion.pl: not found
sh: 1: GCcontent.pl: not found
sh: 1: rmshortseq_noN.pl: not found
sh: 1: getanycolumnuni.pl: not found
sh: 1: rmlistedseq.pl: not found
sh: 1: fasta-reformat.pl: not found
mkdir: cannot create directory ‘RMask_denovoPrediction_protFiltered’: File exists
RepeatMasker::setspecies: Could not find user specified library ../Lake_trout_RepeatModeler/Lake_trout_REPEAT_LIBRARY-families.fanoProtFinal, or the file is empty.
mkdir: cannot create directory ‘RMask_denovoPlusDfam’: File exists
mkdir: cannot create directory ‘final_repeat_mask’: File exists
gzip: ./RMask_denovoPrediction_protFiltered/*.cat.gz: No such file or directory
gzip: ./RMask_denovoPlusDfam/*.cat.gz: No such file or directory
cat: './RMask_denovoPrediction_protFiltered/*.cat': No such file or directory
cat: './RMask_denovoPlusDfam/*.cat': No such file or directory
gzip: ./RMask_denovoPrediction_protFiltered/*.cat: No such file or directory
gzip: ./RMask_denovoPlusDfam/*.cat: No such file or directory
-----------------------------------------------------

**Comment by dmacguigan** [comment]
@Ozzborne are you using the latest version of the pipeline (0.2.5)? I know earlier you said you were using an older version. I made some changes to deal with a ProtExcluder bug.

I just ran step 1 and 2 last week successfully on Bottlerocket, so it should work with the latest scripts.

**Comment by Ozzborne** [comment]
Yes, I am. After having an issue I updated to the latest script and 0.2.5 still has the following line:

/home/krablab/Documents/apps/ProtExcluder/ProtExcluder.pl ${SPECIES}_blastx_uniprot_TEfiltered_e10.out ../${SPECIES}_RepeatModeler/${REPEAT_LIBRARY_NAME}-families.fa

The absence of ProtExcluder.pl in that directory gave me the following error: 

/home/krablab/Documents/CO_data/LT_repeats/Ref_genome//scripts/run_repeatMasker.sh: line 36: /home/krablab/Documents/apps/ProtExcluder1.2/ProtExcluder.pl: No such file or directory

I then copied that ProtExcluder.pl from the https://github.com/NBISweden/ProtExcluder/blob/master/ProtExcluder.pl and updated the paths in that script. That fixed that issue. But then I got an error message saying that mspesl-sfetch.pl was not found in /home/krablab/Documents/apps/ProtExcluder1.2/. Which is, indeed also missing. I am not sure what happened since you ran it but maybe I need to re-install the ProtExcluder software.

**Comment by Ozzborne** [comment]
Ah, I think it was a directory structure issue. I didn't have the Genome_dir embedded in the Annotation_dir directory exactly as you recommended. I was calling the full path to the Genome_dir and that was throwing it off somehow. Sorry for the confusion.

**Comment by dmacguigan** [comment]
The file `/home/krablab/Documents/apps/ProtExcluder/ProtExcluder.pl` definitely exists. Your error must be generated from an older version of the script since it's using the path **apps/ProtExcluder1.2** instead of **apps/ProtExcluder**.

Yes, `GENOME_DIR` needs to be nested within `ANNOTATION_DIR`.
