### ISSUE TITLE
Issues with getting Braker step to run

### ISSUE THREAD

**Issue by Ozzborne** [KrabbenhoftLab/genome_annotation_pipeline#2]
Hi Dan,

I am having trouble getting the Braker step of the pipeline to run on CCR. Below is the content of the BRAKER.err file from the logFiles directory.

If it helps, my annotation directory is here.
/projects/academic/tkrabben/Osborne/LT_annotations/SE08

mkdir: cannot create directory 'SE08_BRAKER': File exists
[WARN  tini (273493)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
#**********************************************************************************
#                               BRAKER CONFIGURATION
#**********************************************************************************
# BRAKER CALL: /opt/BRAKER/scripts/braker.pl --genome=Genome/SE08_Flye_Medaka_Pilon3_Purge_HiC_RagTag_GapCloser_Pilon1.masked.fasta --bam=SE08_HISAT2/SE08.sorted.rna.bam --prot_seq=/vscratch/grp-tkrabben/Osborne/LT>
# Sun Jan  7 16:35:35 2024: braker.pl version 3.0.6
# Sun Jan  7 16:35:35 2024:Both protein and RNA-Seq data in input detected. BRAKER will be executed in ETP mode (BRAKER3).
#*********
# Sun Jan  7 16:35:35 2024: Configuring of BRAKER for using external tools...
# Sun Jan  7 16:35:35 2024: Trying to set $AUGUSTUS_CONFIG_PATH...
# Sun Jan  7 16:35:35 2024: Found environment variable $AUGUSTUS_CONFIG_PATH.
# Sun Jan  7 16:35:35 2024: Checking /usr/share/augustus/config/ as potential path for $AUGUSTUS_CONFIG_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $AUGUSTUS_CONFIG_PATH to /usr/share/augustus/config/!
# Sun Jan  7 16:35:35 2024: WARNING: in file /opt/BRAKER/scripts/braker.pl at line 1894
AUGUSTUS_CONFIG_PATH/species (in this case /usr/share/augustus/config//species) is not writeable. BRAKER will try to copy the AUGUSTUS config directory to a writeable location.
#**********************************************************************************
#                               BRAKER CONFIGURATION
#**********************************************************************************
# BRAKER CALL: /opt/BRAKER/scripts/braker.pl --genome=Genome/SE08_Flye_Medaka_Pilon3_Purge_HiC_RagTag_GapCloser_Pilon1.masked.fasta --bam=SE08_HISAT2/SE08.sorted.rna.bam --prot_seq=/vscratch/grp-tkrabben/Osborne/LT>
# Sun Jan  7 16:35:35 2024: braker.pl version 3.0.6
# Sun Jan  7 16:35:35 2024:Both protein and RNA-Seq data in input detected. BRAKER will be executed in ETP mode (BRAKER3).
#*********
# Sun Jan  7 16:35:35 2024: Configuring of BRAKER for using external tools...
# Sun Jan  7 16:35:35 2024: Trying to set $AUGUSTUS_CONFIG_PATH...
# Sun Jan  7 16:35:35 2024: Found environment variable $AUGUSTUS_CONFIG_PATH.
# Sun Jan  7 16:35:35 2024: Checking /usr/share/augustus/config/ as potential path for $AUGUSTUS_CONFIG_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $AUGUSTUS_CONFIG_PATH to /usr/share/augustus/config/!
# Sun Jan  7 16:35:35 2024: WARNING: in file /opt/BRAKER/scripts/braker.pl at line 1894
AUGUSTUS_CONFIG_PATH/species (in this case /usr/share/augustus/config//species) is not writeable. BRAKER will try to copy the AUGUSTUS config directory to a writeable location.
# Sun Jan  7 16:35:35 2024: Trying to set $AUGUSTUS_BIN_PATH...
# Sun Jan  7 16:35:35 2024: Found environment variable $AUGUSTUS_BIN_PATH.
# Sun Jan  7 16:35:35 2024: Checking /usr/bin/ as potential path for $AUGUSTUS_BIN_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $AUGUSTUS_BIN_PATH to /usr/bin/!
# Sun Jan  7 16:35:35 2024: Trying to set $AUGUSTUS_SCRIPTS_PATH...
# Sun Jan  7 16:35:35 2024: Found environment variable $AUGUSTUS_SCRIPTS_PATH.
# Sun Jan  7 16:35:35 2024: Checking /usr/share/augustus/scripts/ as potential path for $AUGUSTUS_SCRIPTS_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $AUGUSTUS_SCRIPTS_PATH to /usr/share/augustus/scripts/!
# Sun Jan  7 16:35:35 2024: WARNING: BRAKER will copy the
 AUGUSTUS_CONFIG folder into your home directory!
# Sun Jan  7 16:35:35 2024: WARNING: $AUGUSTUS_CONFIG_PATH/species (in this case /usr/share/augustus/config//species ) is not writeable.
*** IMPORTANT: Resetting $AUGUSTUS_CONFIG_PATH=/projects/academic/tkrabben/Osborne/LT_annotations/SE08/.augustus because BRAKER requires a writable location!
# Sun Jan  7 16:35:35 2024: Trying to set $PYTHON3_PATH...
# Sun Jan  7 16:35:35 2024: Did not find environment variable $PYTHON3_PATH.
# Sun Jan  7 16:35:35 2024: Trying to guess PYTHON3_PATH from location of python3 executable that is available in your $PATH
# Sun Jan  7 16:35:35 2024: Checking /opt/conda/bin as potential path for $PYTHON3_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $PYTHON3_PATH to /opt/conda/bin!
# Sun Jan  7 16:35:35 2024: Trying to set $GENEMARK_PATH...
# Sun Jan  7 16:35:35 2024: Found command line argument $GENEMARK_PATH.
# Sun Jan  7 16:35:35 2024: Checking /gmes as potential path for $GENEMARK_PATH.
#*********
# WARNING: /gmes is not a directory. Will not set $GENEMARK_PATH to /gmes!
****
#*********
# Sun Jan  7 16:35:35 2024: Found environment variable $GENEMARK_PATH.
# Sun Jan  7 16:35:35 2024: Checking /opt/ETP/bin as potential path for $GENEMARK_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $GENEMARK_PATH to /opt/ETP/bin!
# Sun Jan  7 16:35:35 2024: Trying to set $BAMTOOLS_PATH...
# Sun Jan  7 16:35:35 2024: Did not find environment variable $BAMTOOLS_PATH.
# Sun Jan  7 16:35:35 2024: Trying to guess BAMTOOLS_PATH from location of bamtools executable that is available in your $PATH
# Sun Jan  7 16:35:35 2024: Checking /usr/bin as potential path for $BAMTOOLS_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $BAMTOOLS_PATH to /usr/bin!
# Sun Jan  7 16:35:35 2024: Trying to set $SAMTOOLS_PATH...
# Sun Jan  7 16:35:35 2024: Did not find environment variable $SAMTOOLS_PATH.
# Sun Jan  7 16:35:35 2024: Trying to guess SAMTOOLS_PATH from location of samtools executable that is available in your $PATH
# Sun Jan  7 16:35:35 2024: Checking /usr/bin as potential path for $SAMTOOLS_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $SAMTOOLS_PATH to /usr/bin!
# Sun Jan  7 16:35:35 2024: Trying to set $DIAMOND_PATH...
# Sun Jan  7 16:35:35 2024: Did not find environment variable $DIAMOND_PATH.
# Sun Jan  7 16:35:35 2024: Trying to guess DIAMOND_PATH from location of diamond executable that is available in your $PATH
# Sun Jan  7 16:35:35 2024: Checking /opt/ETP/tools as potential path for $DIAMOND_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $DIAMOND_PATH to /opt/ETP/tools!
# Sun Jan  7 16:35:35 2024: Trying to set $PROTHINT_PATH...
# Sun Jan  7 16:35:35 2024: Did not find environment variable $PROTHINT_PATH.
# Sun Jan  7 16:35:35 2024: Trying to guess PROTHINT_PATH from location of prothint.py executable that is available in your $PATH
# Sun Jan  7 16:35:35 2024: Checking /opt/ETP/bin/gmes/ProtHint/bin as potential path for $PROTHINT_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $PROTHINT_PATH to /opt/ETP/bin/gmes/ProtHint/bin!
# Sun Jan  7 16:35:35 2024: Trying to set $TSEBRA_PATH...
# Sun Jan  7 16:35:35 2024: Did not find environment variable $TSEBRA_PATH.
# Sun Jan  7 16:35:35 2024: Trying to guess TSEBRA_PATH from location of tsebra.py executable that is available in your $PATH
# Sun Jan  7 16:35:35 2024: Checking /opt/TSEBRA/bin as potential path for $TSEBRA_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $TSEBRA_PATH to /opt/TSEBRA/bin!
# Sun Jan  7 16:35:35 2024: Trying to set $CDBTOOLS_PATH...
# Sun Jan  7 16:35:35 2024: Did not find environment variable $CDBTOOLS_PATH.
# Sun Jan  7 16:35:35 2024: Trying to guess CDBTOOLS_PATH from location of cdbfasta executable that is available in your $PATH
# Sun Jan  7 16:35:35 2024: Checking /opt/cdbfasta as potential path for $CDBTOOLS_PATH.
# Sun Jan  7 16:35:35 2024: Success! Setting $CDBTOOLS_PATH to /opt/cdbfasta!
# Sun Jan  7 16:35:36 2024: ERROR: in file /opt/BRAKER/scripts/braker.pl at line 3585
protein sequence file /vscratch/grp-tkrabben/Osborne/LT_genomes/orthodbv11_metazoan_Salmonidae_proteins_refseq.fasta does not exist.
[WARN  tini (273547)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
### READING GENE PREDICTION: [SE08_BRAKER/braker.gtf]
Traceback (most recent call last):
  File "/opt/TSEBRA/bin/tsebra.py", line 235, in <module>
    main()
  File "/opt/TSEBRA/bin/tsebra.py", line 67, in main
    anno[-1].addGtf()
  File "/opt/TSEBRA/bin/genome_anno.py", line 297, in addGtf
    with open (self.path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'SE08_BRAKER/braker.gtf'

**Comment by dmacguigan** [comment]
Can you confirm that the file `/vscratch/grp-tkrabben/Osborne/LT_genomes/orthodbv11_metazoan_Salmonidae_proteins_refseq.fasta` exists? I would, but I'm not at my computer right now.

**Comment by Ozzborne** [comment]
Yes, it's there.  I noticed it was saying it didn't exist. I also confirmed it's a normal protein fasta format. 

ls -l /vscratch/grp-tkrabben/Osborne/LT_genomes/orthodbv11_metazoan_Salmonidae_proteins_refseq.fasta
-rw-rw-r-- 1 caosborn grp-tkrabben 9491295753 Dec 21 11:16 /vscratch/grp-tkrabben/Osborne/LT_genomes/orthodbv11_metazoan_Salmonidae_proteins_refseq.fasta


format

(base) caosborn@vortex-future:/projects/academic/tkrabben/Osborne/LT_annotations/SE08$ head /vscratch/grp-tkrabben/Osborne/LT_genomes/orthodbv11_metazoan_Salmonidae_proteins_refseq.fasta
>10020_0:000000 10020_0
MADRLTQLQDAVNSLADQFCNAIGVLQQCGPPTSFNNIQSAINKDQPANPTEEYAQLFAALIARTAKDIDVLIDSLPSEESTAALQAEM
>10020_0:000001 10020_0
MEETQEPPAMTVHLLADAGHGWLLQQALDQLLDHICPEVRLFQVSERVRPVKYYGKSHPRRCEFPGMSVWLFLDERLGQERLCHVLDSLQCAPWRCLPAQGRPCPYLPAKQEIYSLDSQMPTWSVRQCRDGPEILRITLHCGFDNYEDAIRLYGMILQREATVQKSSVCFFVLYTTPSFALQLSLKQLPPGTSVDPQESSVLQFRVQEIGQLVPLLPNPCVPISRTRWRTQDYDGHTILLQVQLSPGPGVENGELSFLGALGSRLASGCAQRPMEWRTQRSRSRRFKVRSLEFPEPRGTADSSDGPSWRSPGLASQVSSSATSSWPHLPPHVLKPAWGMNEDGFQKLEAETDVDTGFTIINPEPVVNSLSKDLETRLPPSCPEEATSLRKAAPDVRVCPLSLAGPKELGARKIISTCSHRLPIQGEEKEEEEFFI

**Comment by dmacguigan** [comment]
Hm. Can you try copying `orthodbv11_metazoan_Salmonidae_proteins_refseq.fasta` into `/projects/academic/tkrabben/Osborne/LT_annotations/SE08` (assuming this where you're running the annotation pipeline)? The modify the protein fasta path in the config file and restart BRAKER.

**Comment by Ozzborne** [comment]
That did the trick! Thanks, Dan.

**Comment by dmacguigan** [comment]
Nice! This is an issue with using Singularity to run BRAKER, I'll update the documentation.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dmacguigan** [comment]
Config file and scripts updated to note that `PROT_FASTA` must be nested within `ANNOTATION_DIR_CLUSTER`
